// Generated by LiveScript 1.2.0
(function(){
  module.exports = {
    Permit: require('./permit'),
    container: require('./container'),
    factory: require('./factory'),
    mixin: require('./mixin'),
    registry: require('./registry')
  };
}).call(this);
