// Generated by LiveScript 1.2.0
(function(){
  var Debugger, mixin, permitMixin, Observable, Activation, Registry, Repo, Permit;
  Debugger = require('../util').Debugger;
  mixin = require('../mixin');
  permitMixin = require('./mixin');
  Observable = mixin.Observable;
  Activation = permitMixin.Activation;
  Registry = permitMixin.Registry;
  Repo = permitMixin.Repo;
  module.exports = Permit = (function(){
    Permit.displayName = 'Permit';
    var prototype = Permit.prototype, constructor = Permit;
    importAll$(prototype, arguments[0]);
    importAll$(prototype, arguments[1]);
    importAll$(prototype, arguments[2]);
    importAll$(prototype, arguments[3]);
    importAll$(prototype, arguments[4]);
    function Permit(name, description, debugging){
      this.name = name;
      this.description = description != null ? description : '';
      this.debugging = debugging;
      this.matchEnabled = false;
      if (this.activate && this.autoActivate) {
        this.activate();
      }
      this._register();
      this.init();
      this;
    }
    prototype.init = function(){
      this.debug('permit init');
      this.applier().apply('static');
      return this;
    };
    prototype.match = function(accessRequest){
      return true;
    };
    prototype.rules = function(){
      return {};
    };
    return Permit;
  }(Activation, Observable, Registry, Repo, Debugger));
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
