// Generated by LiveScript 1.2.0
(function(){
  module.exports = {
    autoActivate: true,
    activate: function(){
      this.active = true;
      if (this.register) {
        return this.register();
      }
    },
    deactivate: function(){
      this.active = false;
      if (this.unregister) {
        return this.unregister();
      }
    }
  };
}).call(this);
