// Generated by LiveScript 1.2.0
(function(){
  module.exports = [
    {
      _register: function(){
        this.debug('register permit', this);
        return this.registry().register(this);
      },
      _unregister: function(){
        return this.registry().unregister(this);
      }
    }, this.get = function(name){
      return constructor.registry.get(name);
    }, {
      registry: function(){
        return constructor.registry;
      }
    }
  ];
}).call(this);
