// Generated by LiveScript 1.2.0
(function(){
  module.exports = {
    clean: function(){
      this.repo().clean();
      if (this.applier) {
        return this.applier().clean();
      }
    },
    canRules: function(){
      return this.repo().canRules();
    },
    cannotRules: function(){
      return this.repo().cannotRules();
    },
    repo: function(){
      return this._repo;
    }
  };
}).call(this);
